version: '3'

services:
  postgres:
    image: postgres:14
    restart: "unless-stopped"
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 1s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: egghead
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_SSL_MODE: disable
      ENV: development
      SERVER_PORT: 3005
      SERVICE_NAME: egghead
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

volumes:
  postgres_data: